// <auto-generated />
using System;
using Example.MultiTenantData.DA.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Example.MultiTenantData.DA.EF.Deploy.Migrations
{
    [DbContext(typeof(MtDbContext))]
    [Migration("20240628140724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exmt")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Example.MultiTenantData.DA.Entities.ReferenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceEntity", "exmt");
                });

            modelBuilder.Entity("Example.MultiTenantData.DA.Entities.SegregatedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReferenceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceEntityId");

                    b.ToTable("SegregatedEntity", "exmt");
                });

            modelBuilder.Entity("Example.MultiTenantData.DA.Entities.SegregatedEntity", b =>
                {
                    b.HasOne("Example.MultiTenantData.DA.Entities.ReferenceEntity", "ReferenceEntity")
                        .WithMany("SegregatedEntities")
                        .HasForeignKey("ReferenceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceEntity");
                });

            modelBuilder.Entity("Example.MultiTenantData.DA.Entities.ReferenceEntity", b =>
                {
                    b.Navigation("SegregatedEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
