USE [master]
GO

/****** Object:  Database [db-shared]    Script Date: 03/04/2024 16:58:40 ******/
CREATE DATABASE [db-shared]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db-shared', FILENAME = N'/var/opt/mssql/data/db-shared.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db-shared_log', FILENAME = N'/var/opt/mssql/data/db-shared_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db-shared] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db-shared].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db-shared] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db-shared] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db-shared] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db-shared] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db-shared] SET ARITHABORT OFF 
GO
ALTER DATABASE [db-shared] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db-shared] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db-shared] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db-shared] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db-shared] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db-shared] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db-shared] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db-shared] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db-shared] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db-shared] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db-shared] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db-shared] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db-shared] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db-shared] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db-shared] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db-shared] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [db-shared] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db-shared] SET RECOVERY FULL 
GO
ALTER DATABASE [db-shared] SET  MULTI_USER 
GO
ALTER DATABASE [db-shared] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db-shared] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db-shared] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db-shared] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db-shared] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db-shared] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'db-shared', N'ON'
GO
ALTER DATABASE [db-shared] SET QUERY_STORE = ON
GO
ALTER DATABASE [db-shared] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO


/****** Object:  Database [db-tenantc]    Script Date: 03/04/2024 16:58:40 ******/
CREATE DATABASE [db-tenantc]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db-tenantc', FILENAME = N'/var/opt/mssql/data/db-tenantc.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db-tenantc_log', FILENAME = N'/var/opt/mssql/data/db-tenantc_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [db-tenantc] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db-tenantc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db-tenantc] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db-tenantc] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db-tenantc] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db-tenantc] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db-tenantc] SET ARITHABORT OFF 
GO
ALTER DATABASE [db-tenantc] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [db-tenantc] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db-tenantc] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db-tenantc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db-tenantc] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db-tenantc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db-tenantc] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db-tenantc] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db-tenantc] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db-tenantc] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db-tenantc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db-tenantc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db-tenantc] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db-tenantc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db-tenantc] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db-tenantc] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [db-tenantc] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db-tenantc] SET RECOVERY FULL 
GO
ALTER DATABASE [db-tenantc] SET  MULTI_USER 
GO
ALTER DATABASE [db-tenantc] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db-tenantc] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db-tenantc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db-tenantc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db-tenantc] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db-tenantc] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'db-tenantc', N'ON'
GO
ALTER DATABASE [db-tenantc] SET QUERY_STORE = ON
GO
ALTER DATABASE [db-tenantc] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
